// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"

	"github.com/XiaoMi/talos-sdk-golang/thrift/topic"

	"git.apache.org/thrift.git/lib/go/thrift"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  CreateTopicResponse createTopic(CreateTopicRequest request)")
	fmt.Fprintln(os.Stderr, "  void deleteTopic(DeleteTopicRequest request)")
	fmt.Fprintln(os.Stderr, "  void changeTopicAttribute(ChangeTopicAttributeRequest request)")
	fmt.Fprintln(os.Stderr, "  DescribeTopicResponse describeTopic(DescribeTopicRequest request)")
	fmt.Fprintln(os.Stderr, "  GetDescribeInfoResponse getDescribeInfo(GetDescribeInfoRequest request)")
	fmt.Fprintln(os.Stderr, "  ListTopicsInfoResponse listTopicsInfo()")
	fmt.Fprintln(os.Stderr, "  ListTopicsResponse listTopics()")
	fmt.Fprintln(os.Stderr, "  ListTopicsResponse getBindTopics()")
	fmt.Fprintln(os.Stderr, "  void setTopicQuota(SetTopicQuotaRequest request)")
	fmt.Fprintln(os.Stderr, "  QueryTopicQuotaResponse queryTopicQuota(QueryTopicQuotaRequest request)")
	fmt.Fprintln(os.Stderr, "  void deleteTopicQuota(DeleteTopicQuotaRequest request)")
	fmt.Fprintln(os.Stderr, "  void setPermission(SetPermissionRequest request)")
	fmt.Fprintln(os.Stderr, "  void revokePermission(RevokePermissionRequest request)")
	fmt.Fprintln(os.Stderr, "  ListPermissionResponse listPermission(ListPermissionRequest request)")
	fmt.Fprintln(os.Stderr, "  GetPermissionResponse getPermission(GetPermissionRequest request)")
	fmt.Fprintln(os.Stderr, "  void addSubResourceName(AddSubResourceNameRequest request)")
	fmt.Fprintln(os.Stderr, "  Version getServiceVersion()")
	fmt.Fprintln(os.Stderr, "  void validClientVersion(Version clientVersion)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := topic.NewTopicServiceClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "createTopic":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "CreateTopic requires 1 args")
			flag.Usage()
		}
		arg46 := flag.Arg(1)
		mbTrans47 := thrift.NewTMemoryBufferLen(len(arg46))
		defer mbTrans47.Close()
		_, err48 := mbTrans47.WriteString(arg46)
		if err48 != nil {
			Usage()
			return
		}
		factory49 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt50 := factory49.GetProtocol(mbTrans47)
		argvalue0 := topic.NewCreateTopicRequest()
		err51 := argvalue0.Read(jsProt50)
		if err51 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreateTopic(value0))
		fmt.Print("\n")
		break
	case "deleteTopic":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteTopic requires 1 args")
			flag.Usage()
		}
		arg52 := flag.Arg(1)
		mbTrans53 := thrift.NewTMemoryBufferLen(len(arg52))
		defer mbTrans53.Close()
		_, err54 := mbTrans53.WriteString(arg52)
		if err54 != nil {
			Usage()
			return
		}
		factory55 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt56 := factory55.GetProtocol(mbTrans53)
		argvalue0 := topic.NewDeleteTopicRequest()
		err57 := argvalue0.Read(jsProt56)
		if err57 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteTopic(value0))
		fmt.Print("\n")
		break
	case "changeTopicAttribute":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ChangeTopicAttribute requires 1 args")
			flag.Usage()
		}
		arg58 := flag.Arg(1)
		mbTrans59 := thrift.NewTMemoryBufferLen(len(arg58))
		defer mbTrans59.Close()
		_, err60 := mbTrans59.WriteString(arg58)
		if err60 != nil {
			Usage()
			return
		}
		factory61 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt62 := factory61.GetProtocol(mbTrans59)
		argvalue0 := topic.NewChangeTopicAttributeRequest()
		err63 := argvalue0.Read(jsProt62)
		if err63 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ChangeTopicAttribute(value0))
		fmt.Print("\n")
		break
	case "describeTopic":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeTopic requires 1 args")
			flag.Usage()
		}
		arg64 := flag.Arg(1)
		mbTrans65 := thrift.NewTMemoryBufferLen(len(arg64))
		defer mbTrans65.Close()
		_, err66 := mbTrans65.WriteString(arg64)
		if err66 != nil {
			Usage()
			return
		}
		factory67 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt68 := factory67.GetProtocol(mbTrans65)
		argvalue0 := topic.NewDescribeTopicRequest()
		err69 := argvalue0.Read(jsProt68)
		if err69 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DescribeTopic(value0))
		fmt.Print("\n")
		break
	case "getDescribeInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDescribeInfo requires 1 args")
			flag.Usage()
		}
		arg70 := flag.Arg(1)
		mbTrans71 := thrift.NewTMemoryBufferLen(len(arg70))
		defer mbTrans71.Close()
		_, err72 := mbTrans71.WriteString(arg70)
		if err72 != nil {
			Usage()
			return
		}
		factory73 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt74 := factory73.GetProtocol(mbTrans71)
		argvalue0 := topic.NewGetDescribeInfoRequest()
		err75 := argvalue0.Read(jsProt74)
		if err75 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetDescribeInfo(value0))
		fmt.Print("\n")
		break
	case "listTopicsInfo":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "ListTopicsInfo requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.ListTopicsInfo())
		fmt.Print("\n")
		break
	case "listTopics":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "ListTopics requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.ListTopics())
		fmt.Print("\n")
		break
	case "getBindTopics":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetBindTopics requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetBindTopics())
		fmt.Print("\n")
		break
	case "setTopicQuota":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetTopicQuota requires 1 args")
			flag.Usage()
		}
		arg76 := flag.Arg(1)
		mbTrans77 := thrift.NewTMemoryBufferLen(len(arg76))
		defer mbTrans77.Close()
		_, err78 := mbTrans77.WriteString(arg76)
		if err78 != nil {
			Usage()
			return
		}
		factory79 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt80 := factory79.GetProtocol(mbTrans77)
		argvalue0 := topic.NewSetTopicQuotaRequest()
		err81 := argvalue0.Read(jsProt80)
		if err81 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SetTopicQuota(value0))
		fmt.Print("\n")
		break
	case "queryTopicQuota":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryTopicQuota requires 1 args")
			flag.Usage()
		}
		arg82 := flag.Arg(1)
		mbTrans83 := thrift.NewTMemoryBufferLen(len(arg82))
		defer mbTrans83.Close()
		_, err84 := mbTrans83.WriteString(arg82)
		if err84 != nil {
			Usage()
			return
		}
		factory85 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt86 := factory85.GetProtocol(mbTrans83)
		argvalue0 := topic.NewQueryTopicQuotaRequest()
		err87 := argvalue0.Read(jsProt86)
		if err87 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryTopicQuota(value0))
		fmt.Print("\n")
		break
	case "deleteTopicQuota":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteTopicQuota requires 1 args")
			flag.Usage()
		}
		arg88 := flag.Arg(1)
		mbTrans89 := thrift.NewTMemoryBufferLen(len(arg88))
		defer mbTrans89.Close()
		_, err90 := mbTrans89.WriteString(arg88)
		if err90 != nil {
			Usage()
			return
		}
		factory91 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt92 := factory91.GetProtocol(mbTrans89)
		argvalue0 := topic.NewDeleteTopicQuotaRequest()
		err93 := argvalue0.Read(jsProt92)
		if err93 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteTopicQuota(value0))
		fmt.Print("\n")
		break
	case "setPermission":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetPermission requires 1 args")
			flag.Usage()
		}
		arg94 := flag.Arg(1)
		mbTrans95 := thrift.NewTMemoryBufferLen(len(arg94))
		defer mbTrans95.Close()
		_, err96 := mbTrans95.WriteString(arg94)
		if err96 != nil {
			Usage()
			return
		}
		factory97 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt98 := factory97.GetProtocol(mbTrans95)
		argvalue0 := topic.NewSetPermissionRequest()
		err99 := argvalue0.Read(jsProt98)
		if err99 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SetPermission(value0))
		fmt.Print("\n")
		break
	case "revokePermission":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RevokePermission requires 1 args")
			flag.Usage()
		}
		arg100 := flag.Arg(1)
		mbTrans101 := thrift.NewTMemoryBufferLen(len(arg100))
		defer mbTrans101.Close()
		_, err102 := mbTrans101.WriteString(arg100)
		if err102 != nil {
			Usage()
			return
		}
		factory103 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt104 := factory103.GetProtocol(mbTrans101)
		argvalue0 := topic.NewRevokePermissionRequest()
		err105 := argvalue0.Read(jsProt104)
		if err105 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RevokePermission(value0))
		fmt.Print("\n")
		break
	case "listPermission":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ListPermission requires 1 args")
			flag.Usage()
		}
		arg106 := flag.Arg(1)
		mbTrans107 := thrift.NewTMemoryBufferLen(len(arg106))
		defer mbTrans107.Close()
		_, err108 := mbTrans107.WriteString(arg106)
		if err108 != nil {
			Usage()
			return
		}
		factory109 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt110 := factory109.GetProtocol(mbTrans107)
		argvalue0 := topic.NewListPermissionRequest()
		err111 := argvalue0.Read(jsProt110)
		if err111 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ListPermission(value0))
		fmt.Print("\n")
		break
	case "getPermission":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetPermission requires 1 args")
			flag.Usage()
		}
		arg112 := flag.Arg(1)
		mbTrans113 := thrift.NewTMemoryBufferLen(len(arg112))
		defer mbTrans113.Close()
		_, err114 := mbTrans113.WriteString(arg112)
		if err114 != nil {
			Usage()
			return
		}
		factory115 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt116 := factory115.GetProtocol(mbTrans113)
		argvalue0 := topic.NewGetPermissionRequest()
		err117 := argvalue0.Read(jsProt116)
		if err117 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetPermission(value0))
		fmt.Print("\n")
		break
	case "addSubResourceName":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "AddSubResourceName requires 1 args")
			flag.Usage()
		}
		arg118 := flag.Arg(1)
		mbTrans119 := thrift.NewTMemoryBufferLen(len(arg118))
		defer mbTrans119.Close()
		_, err120 := mbTrans119.WriteString(arg118)
		if err120 != nil {
			Usage()
			return
		}
		factory121 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt122 := factory121.GetProtocol(mbTrans119)
		argvalue0 := topic.NewAddSubResourceNameRequest()
		err123 := argvalue0.Read(jsProt122)
		if err123 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.AddSubResourceName(value0))
		fmt.Print("\n")
		break
	case "getServiceVersion":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetServiceVersion requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetServiceVersion())
		fmt.Print("\n")
		break
	case "validClientVersion":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ValidClientVersion requires 1 args")
			flag.Usage()
		}
		arg124 := flag.Arg(1)
		mbTrans125 := thrift.NewTMemoryBufferLen(len(arg124))
		defer mbTrans125.Close()
		_, err126 := mbTrans125.WriteString(arg124)
		if err126 != nil {
			Usage()
			return
		}
		factory127 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt128 := factory127.GetProtocol(mbTrans125)
		argvalue0 := topic.NewVersion()
		err129 := argvalue0.Read(jsProt128)
		if err129 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ValidClientVersion(value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
