// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package common

import (
	"../../../thrift"
	"bytes"
	"fmt"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

const GALAXY_TALOS_DEFAULT_SERVICE_ENDPOINT = "http://talos.api.xiaomi.com"
const GALAXY_TALOS_DEFAULT_SECURE_SERVICE_ENDPOINT = "https://talos.api.xiaomi.com"
const GALAXY_TALOS_CLIENT_TIMEOUT_MILLI_SECS_DEFAULT = 10000
const GALAXY_TALOS_CLIENT_ADMIN_TIMEOUT_MILLI_SECS_DEFAULT = 30000
const GALAXY_TALOS_CLIENT_CONN_TIMECOUT_MILLI_SECS_DEFAULT = 5000
const TALOS_API_ROOT_PATH = "/v1/api"
const TALOS_TOPIC_SERVICE_PATH = "/v1/api/topic"
const TALOS_MESSAGE_SERVICE_PATH = "/v1/api/message"
const TALOS_QUOTA_SERVICE_PATH = "/v1/api/quota"
const TALOS_CONSUMER_SERVICE_PATH = "/v1/api/consumer"
const TALOS_IDENTIFIER_DELIMITER = "#"
const TALOS_NAME_REGEX = "^(?!_)(?!-)(?!.*?_$)[a-zA-Z0-9_-]+$"
const TALOS_NAME_BODY_REGEX = "^[a-zA-Z0-9_-]+$"
const TALOS_NAME_HEAD_REGEX = "^[-_]+|_$"
const TALOS_SINGLE_MESSAGE_BYTES_MINIMAL = 1
const TALOS_SINGLE_MESSAGE_BYTES_MAXIMAL = 10485760
const TALOS_MESSAGE_BLOCK_BYTES_MAXIMAL = 20971520
const TALOS_PARTITION_KEY_LENGTH_MINIMAL = 1
const TALOS_PARTITION_KEY_LENGTH_MAXIMAL = 256
const TALOS_CLOUD_TOPIC_NAME_DELIMITER = "/"
const TALOS_CLOUD_ORG_PREFIX = "CL"
const TALOS_CLOUD_TEAM_PREFIX = "CI"
const TALOS_CLOUD_AK_PREFIX = "AK"
const TALOS_GALAXY_AK_PREFIX = "EAK"

var ERROR_BACKOFF map[ErrorCode]int64
var ERROR_RETRY_TYPE map[ErrorCode]RetryType

func init() {
	ERROR_BACKOFF = map[ErrorCode]int64{
		5:  1000,
		6:  1000,
		17: 2000,
		21: 2000,
		25: 1000,
		2:  1000,
		10: 1000,
		11: 1000,
		12: 1000,
		13: 1000,
		14: 1000,
		15: 1000,
		26: 1000,
	}

	ERROR_RETRY_TYPE = map[ErrorCode]RetryType{
		5:  0,
		6:  0,
		17: 0,
		21: 0,
		25: 0,
		2:  1,
		10: 1,
		11: 1,
		12: 1,
		13: 1,
		14: 1,
		15: 1,
		26: 1,
	}

}
