// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package message

import (
	"bytes"
	"fmt"
	"github.com/XiaoMi/talos-sdk-golang/talos/thrift/common"
	"github.com/XiaoMi/talos-sdk-golang/talos/thrift/topic"
	"github.com/XiaoMi/talos-sdk-golang/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = common.GoUnusedProtection__
var _ = topic.GoUnusedProtection__
var GoUnusedProtection__ int

type MessageType int64

const (
	MessageType_BINARY   MessageType = 1
	MessageType_UTF8     MessageType = 2
	MessageType_THRIFT   MessageType = 3
	MessageType_AVRO     MessageType = 4
	MessageType_PROTOBUF MessageType = 5
)

func (p MessageType) String() string {
	switch p {
	case MessageType_BINARY:
		return "MessageType_BINARY"
	case MessageType_UTF8:
		return "MessageType_UTF8"
	case MessageType_THRIFT:
		return "MessageType_THRIFT"
	case MessageType_AVRO:
		return "MessageType_AVRO"
	case MessageType_PROTOBUF:
		return "MessageType_PROTOBUF"
	}
	return "<UNSET>"
}

func MessageTypeFromString(s string) (MessageType, error) {
	switch s {
	case "MessageType_BINARY":
		return MessageType_BINARY, nil
	case "MessageType_UTF8":
		return MessageType_UTF8, nil
	case "MessageType_THRIFT":
		return MessageType_THRIFT, nil
	case "MessageType_AVRO":
		return MessageType_AVRO, nil
	case "MessageType_PROTOBUF":
		return MessageType_PROTOBUF, nil
	}
	return MessageType(0), fmt.Errorf("not a valid MessageType string")
}

func MessageTypePtr(v MessageType) *MessageType { return &v }

type MessageOffset int64

const (
	MessageOffset_START_OFFSET  MessageOffset = -1
	MessageOffset_LATEST_OFFSET MessageOffset = -2
)

func (p MessageOffset) String() string {
	switch p {
	case MessageOffset_START_OFFSET:
		return "MessageOffset_START_OFFSET"
	case MessageOffset_LATEST_OFFSET:
		return "MessageOffset_LATEST_OFFSET"
	}
	return "<UNSET>"
}

func MessageOffsetFromString(s string) (MessageOffset, error) {
	switch s {
	case "MessageOffset_START_OFFSET":
		return MessageOffset_START_OFFSET, nil
	case "MessageOffset_LATEST_OFFSET":
		return MessageOffset_LATEST_OFFSET, nil
	}
	return MessageOffset(0), fmt.Errorf("not a valid MessageOffset string")
}

func MessageOffsetPtr(v MessageOffset) *MessageOffset { return &v }

type MessageCompressionType int64

const (
	MessageCompressionType_NONE   MessageCompressionType = 0
	MessageCompressionType_SNAPPY MessageCompressionType = 1
	MessageCompressionType_GZIP   MessageCompressionType = 2
)

func (p MessageCompressionType) String() string {
	switch p {
	case MessageCompressionType_NONE:
		return "MessageCompressionType_NONE"
	case MessageCompressionType_SNAPPY:
		return "MessageCompressionType_SNAPPY"
	case MessageCompressionType_GZIP:
		return "MessageCompressionType_GZIP"
	}
	return "<UNSET>"
}

func MessageCompressionTypeFromString(s string) (MessageCompressionType, error) {
	switch s {
	case "MessageCompressionType_NONE":
		return MessageCompressionType_NONE, nil
	case "MessageCompressionType_SNAPPY":
		return MessageCompressionType_SNAPPY, nil
	case "MessageCompressionType_GZIP":
		return MessageCompressionType_GZIP, nil
	}
	return MessageCompressionType(0), fmt.Errorf("not a valid MessageCompressionType string")
}

func MessageCompressionTypePtr(v MessageCompressionType) *MessageCompressionType { return &v }

type Message struct {
	PartitionKey      *string      `thrift:"partitionKey,1" json:"partitionKey"`
	SequenceNumber    *string      `thrift:"sequenceNumber,2" json:"sequenceNumber"`
	Message           []byte       `thrift:"message,3,required" json:"message"`
	CreateTimestamp   *int64       `thrift:"createTimestamp,4" json:"createTimestamp"`
	AppendTimestamp   *int64       `thrift:"appendTimestamp,5" json:"appendTimestamp"`
	MessageType       *MessageType `thrift:"messageType,6" json:"messageType"`
	SchemaFingerprint *string      `thrift:"SchemaFingerprint,7" json:"SchemaFingerprint"`
}

func NewMessage() *Message {
	return &Message{}
}

var Message_PartitionKey_DEFAULT string

func (p *Message) GetPartitionKey() string {
	if !p.IsSetPartitionKey() {
		return Message_PartitionKey_DEFAULT
	}
	return *p.PartitionKey
}

var Message_SequenceNumber_DEFAULT string

func (p *Message) GetSequenceNumber() string {
	if !p.IsSetSequenceNumber() {
		return Message_SequenceNumber_DEFAULT
	}
	return *p.SequenceNumber
}

func (p *Message) GetMessage() []byte {
	return p.Message
}

var Message_CreateTimestamp_DEFAULT int64

func (p *Message) GetCreateTimestamp() int64 {
	if !p.IsSetCreateTimestamp() {
		return Message_CreateTimestamp_DEFAULT
	}
	return *p.CreateTimestamp
}

var Message_AppendTimestamp_DEFAULT int64

func (p *Message) GetAppendTimestamp() int64 {
	if !p.IsSetAppendTimestamp() {
		return Message_AppendTimestamp_DEFAULT
	}
	return *p.AppendTimestamp
}

var Message_MessageType_DEFAULT MessageType

func (p *Message) GetMessageType() MessageType {
	if !p.IsSetMessageType() {
		return Message_MessageType_DEFAULT
	}
	return *p.MessageType
}

var Message_SchemaFingerprint_DEFAULT string

func (p *Message) GetSchemaFingerprint() string {
	if !p.IsSetSchemaFingerprint() {
		return Message_SchemaFingerprint_DEFAULT
	}
	return *p.SchemaFingerprint
}
func (p *Message) IsSetPartitionKey() bool {
	return p.PartitionKey != nil
}

func (p *Message) IsSetSequenceNumber() bool {
	return p.SequenceNumber != nil
}

func (p *Message) IsSetCreateTimestamp() bool {
	return p.CreateTimestamp != nil
}

func (p *Message) IsSetAppendTimestamp() bool {
	return p.AppendTimestamp != nil
}

func (p *Message) IsSetMessageType() bool {
	return p.MessageType != nil
}

func (p *Message) IsSetSchemaFingerprint() bool {
	return p.SchemaFingerprint != nil
}

func (p *Message) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		case 6:
			if err := p.ReadField6(iprot); err != nil {
				return err
			}
		case 7:
			if err := p.ReadField7(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *Message) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 1: %s", err)
	} else {
		p.PartitionKey = &v
	}
	return nil
}

func (p *Message) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.SequenceNumber = &v
	}
	return nil
}

func (p *Message) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		p.Message = v
	}
	return nil
}

func (p *Message) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 4: %s", err)
	} else {
		p.CreateTimestamp = &v
	}
	return nil
}

func (p *Message) ReadField5(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 5: %s", err)
	} else {
		p.AppendTimestamp = &v
	}
	return nil
}

func (p *Message) ReadField6(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 6: %s", err)
	} else {
		temp := MessageType(v)
		p.MessageType = &temp
	}
	return nil
}

func (p *Message) ReadField7(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 7: %s", err)
	} else {
		p.SchemaFingerprint = &v
	}
	return nil
}

func (p *Message) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("Message"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := p.writeField5(oprot); err != nil {
		return err
	}
	if err := p.writeField6(oprot); err != nil {
		return err
	}
	if err := p.writeField7(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *Message) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetPartitionKey() {
		if err := oprot.WriteFieldBegin("partitionKey", thrift.STRING, 1); err != nil {
			return fmt.Errorf("%T write field begin error 1:partitionKey: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.PartitionKey)); err != nil {
			return fmt.Errorf("%T.partitionKey (1) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 1:partitionKey: %s", p, err)
		}
	}
	return err
}

func (p *Message) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetSequenceNumber() {
		if err := oprot.WriteFieldBegin("sequenceNumber", thrift.STRING, 2); err != nil {
			return fmt.Errorf("%T write field begin error 2:sequenceNumber: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.SequenceNumber)); err != nil {
			return fmt.Errorf("%T.sequenceNumber (2) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 2:sequenceNumber: %s", p, err)
		}
	}
	return err
}

func (p *Message) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("message", thrift.STRING, 3); err != nil {
		return fmt.Errorf("%T write field begin error 3:message: %s", p, err)
	}
	if err := oprot.WriteBinary(p.Message); err != nil {
		return fmt.Errorf("%T.message (3) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 3:message: %s", p, err)
	}
	return err
}

func (p *Message) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetCreateTimestamp() {
		if err := oprot.WriteFieldBegin("createTimestamp", thrift.I64, 4); err != nil {
			return fmt.Errorf("%T write field begin error 4:createTimestamp: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.CreateTimestamp)); err != nil {
			return fmt.Errorf("%T.createTimestamp (4) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 4:createTimestamp: %s", p, err)
		}
	}
	return err
}

func (p *Message) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetAppendTimestamp() {
		if err := oprot.WriteFieldBegin("appendTimestamp", thrift.I64, 5); err != nil {
			return fmt.Errorf("%T write field begin error 5:appendTimestamp: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.AppendTimestamp)); err != nil {
			return fmt.Errorf("%T.appendTimestamp (5) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 5:appendTimestamp: %s", p, err)
		}
	}
	return err
}

func (p *Message) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetMessageType() {
		if err := oprot.WriteFieldBegin("messageType", thrift.I32, 6); err != nil {
			return fmt.Errorf("%T write field begin error 6:messageType: %s", p, err)
		}
		if err := oprot.WriteI32(int32(*p.MessageType)); err != nil {
			return fmt.Errorf("%T.messageType (6) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 6:messageType: %s", p, err)
		}
	}
	return err
}

func (p *Message) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetSchemaFingerprint() {
		if err := oprot.WriteFieldBegin("SchemaFingerprint", thrift.STRING, 7); err != nil {
			return fmt.Errorf("%T write field begin error 7:SchemaFingerprint: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.SchemaFingerprint)); err != nil {
			return fmt.Errorf("%T.SchemaFingerprint (7) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 7:SchemaFingerprint: %s", p, err)
		}
	}
	return err
}

func (p *Message) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Message(%+v)", *p)
}

type MessageIndex struct {
	TopicAndPartition *topic.TopicAndPartition `thrift:"topicAndPartition,1,required" json:"topicAndPartition"`
	MessageOffset     int64                    `thrift:"messageOffset,2,required" json:"messageOffset"`
	HdfsLogFileOffset int64                    `thrift:"hdfsLogFileOffset,3,required" json:"hdfsLogFileOffset"`
	MessageNumber     int32                    `thrift:"messageNumber,4,required" json:"messageNumber"`
}

func NewMessageIndex() *MessageIndex {
	return &MessageIndex{}
}

var MessageIndex_TopicAndPartition_DEFAULT *topic.TopicAndPartition

func (p *MessageIndex) GetTopicAndPartition() *topic.TopicAndPartition {
	if !p.IsSetTopicAndPartition() {
		return MessageIndex_TopicAndPartition_DEFAULT
	}
	return p.TopicAndPartition
}

func (p *MessageIndex) GetMessageOffset() int64 {
	return p.MessageOffset
}

func (p *MessageIndex) GetHdfsLogFileOffset() int64 {
	return p.HdfsLogFileOffset
}

func (p *MessageIndex) GetMessageNumber() int32 {
	return p.MessageNumber
}
func (p *MessageIndex) IsSetTopicAndPartition() bool {
	return p.TopicAndPartition != nil
}

func (p *MessageIndex) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *MessageIndex) ReadField1(iprot thrift.TProtocol) error {
	p.TopicAndPartition = &topic.TopicAndPartition{}
	if err := p.TopicAndPartition.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.TopicAndPartition, err)
	}
	return nil
}

func (p *MessageIndex) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.MessageOffset = v
	}
	return nil
}

func (p *MessageIndex) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		p.HdfsLogFileOffset = v
	}
	return nil
}

func (p *MessageIndex) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 4: %s", err)
	} else {
		p.MessageNumber = v
	}
	return nil
}

func (p *MessageIndex) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("MessageIndex"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *MessageIndex) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("topicAndPartition", thrift.STRUCT, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:topicAndPartition: %s", p, err)
	}
	if err := p.TopicAndPartition.Write(oprot); err != nil {
		return fmt.Errorf("%T error writing struct: %s", p.TopicAndPartition, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:topicAndPartition: %s", p, err)
	}
	return err
}

func (p *MessageIndex) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("messageOffset", thrift.I64, 2); err != nil {
		return fmt.Errorf("%T write field begin error 2:messageOffset: %s", p, err)
	}
	if err := oprot.WriteI64(int64(p.MessageOffset)); err != nil {
		return fmt.Errorf("%T.messageOffset (2) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 2:messageOffset: %s", p, err)
	}
	return err
}

func (p *MessageIndex) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("hdfsLogFileOffset", thrift.I64, 3); err != nil {
		return fmt.Errorf("%T write field begin error 3:hdfsLogFileOffset: %s", p, err)
	}
	if err := oprot.WriteI64(int64(p.HdfsLogFileOffset)); err != nil {
		return fmt.Errorf("%T.hdfsLogFileOffset (3) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 3:hdfsLogFileOffset: %s", p, err)
	}
	return err
}

func (p *MessageIndex) writeField4(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("messageNumber", thrift.I32, 4); err != nil {
		return fmt.Errorf("%T write field begin error 4:messageNumber: %s", p, err)
	}
	if err := oprot.WriteI32(int32(p.MessageNumber)); err != nil {
		return fmt.Errorf("%T.messageNumber (4) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 4:messageNumber: %s", p, err)
	}
	return err
}

func (p *MessageIndex) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageIndex(%+v)", *p)
}

type MessageAndOffset struct {
	Message                *Message `thrift:"message,1,required" json:"message"`
	MessageOffset          int64    `thrift:"messageOffset,2,required" json:"messageOffset"`
	UnHandledMessageNumber *int64   `thrift:"unHandledMessageNumber,3" json:"unHandledMessageNumber"`
}

func NewMessageAndOffset() *MessageAndOffset {
	return &MessageAndOffset{}
}

var MessageAndOffset_Message_DEFAULT *Message

func (p *MessageAndOffset) GetMessage() *Message {
	if !p.IsSetMessage() {
		return MessageAndOffset_Message_DEFAULT
	}
	return p.Message
}

func (p *MessageAndOffset) GetMessageOffset() int64 {
	return p.MessageOffset
}

var MessageAndOffset_UnHandledMessageNumber_DEFAULT int64

func (p *MessageAndOffset) GetUnHandledMessageNumber() int64 {
	if !p.IsSetUnHandledMessageNumber() {
		return MessageAndOffset_UnHandledMessageNumber_DEFAULT
	}
	return *p.UnHandledMessageNumber
}
func (p *MessageAndOffset) IsSetMessage() bool {
	return p.Message != nil
}

func (p *MessageAndOffset) IsSetUnHandledMessageNumber() bool {
	return p.UnHandledMessageNumber != nil
}

func (p *MessageAndOffset) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *MessageAndOffset) ReadField1(iprot thrift.TProtocol) error {
	p.Message = &Message{}
	if err := p.Message.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.Message, err)
	}
	return nil
}

func (p *MessageAndOffset) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.MessageOffset = v
	}
	return nil
}

func (p *MessageAndOffset) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		p.UnHandledMessageNumber = &v
	}
	return nil
}

func (p *MessageAndOffset) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("MessageAndOffset"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *MessageAndOffset) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("message", thrift.STRUCT, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:message: %s", p, err)
	}
	if err := p.Message.Write(oprot); err != nil {
		return fmt.Errorf("%T error writing struct: %s", p.Message, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:message: %s", p, err)
	}
	return err
}

func (p *MessageAndOffset) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("messageOffset", thrift.I64, 2); err != nil {
		return fmt.Errorf("%T write field begin error 2:messageOffset: %s", p, err)
	}
	if err := oprot.WriteI64(int64(p.MessageOffset)); err != nil {
		return fmt.Errorf("%T.messageOffset (2) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 2:messageOffset: %s", p, err)
	}
	return err
}

func (p *MessageAndOffset) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetUnHandledMessageNumber() {
		if err := oprot.WriteFieldBegin("unHandledMessageNumber", thrift.I64, 3); err != nil {
			return fmt.Errorf("%T write field begin error 3:unHandledMessageNumber: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.UnHandledMessageNumber)); err != nil {
			return fmt.Errorf("%T.unHandledMessageNumber (3) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 3:unHandledMessageNumber: %s", p, err)
		}
	}
	return err
}

func (p *MessageAndOffset) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageAndOffset(%+v)", *p)
}

type MessageBlock struct {
	StartMessageOffset  int64                  `thrift:"startMessageOffset,1,required" json:"startMessageOffset"`
	MessageNumber       int32                  `thrift:"messageNumber,2,required" json:"messageNumber"`
	CompressionType     MessageCompressionType `thrift:"compressionType,3,required" json:"compressionType"`
	MessageBlock        []byte                 `thrift:"messageBlock,4,required" json:"messageBlock"`
	MessageBlockSize    *int32                 `thrift:"messageBlockSize,5" json:"messageBlockSize"`
	AppendTimestamp     *int64                 `thrift:"appendTimestamp,6" json:"appendTimestamp"`
	CreateTimestamp     *int64                 `thrift:"createTimestamp,7" json:"createTimestamp"`
	CreateTimestampList []int64                `thrift:"createTimestampList,8" json:"createTimestampList"`
}

func NewMessageBlock() *MessageBlock {
	return &MessageBlock{
		CompressionType: 0,
	}
}

func (p *MessageBlock) GetStartMessageOffset() int64 {
	return p.StartMessageOffset
}

func (p *MessageBlock) GetMessageNumber() int32 {
	return p.MessageNumber
}

func (p *MessageBlock) GetCompressionType() MessageCompressionType {
	return p.CompressionType
}

func (p *MessageBlock) GetMessageBlock() []byte {
	return p.MessageBlock
}

var MessageBlock_MessageBlockSize_DEFAULT int32

func (p *MessageBlock) GetMessageBlockSize() int32 {
	if !p.IsSetMessageBlockSize() {
		return MessageBlock_MessageBlockSize_DEFAULT
	}
	return *p.MessageBlockSize
}

var MessageBlock_AppendTimestamp_DEFAULT int64

func (p *MessageBlock) GetAppendTimestamp() int64 {
	if !p.IsSetAppendTimestamp() {
		return MessageBlock_AppendTimestamp_DEFAULT
	}
	return *p.AppendTimestamp
}

var MessageBlock_CreateTimestamp_DEFAULT int64

func (p *MessageBlock) GetCreateTimestamp() int64 {
	if !p.IsSetCreateTimestamp() {
		return MessageBlock_CreateTimestamp_DEFAULT
	}
	return *p.CreateTimestamp
}

var MessageBlock_CreateTimestampList_DEFAULT []int64

func (p *MessageBlock) GetCreateTimestampList() []int64 {
	return p.CreateTimestampList
}
func (p *MessageBlock) IsSetMessageBlockSize() bool {
	return p.MessageBlockSize != nil
}

func (p *MessageBlock) IsSetAppendTimestamp() bool {
	return p.AppendTimestamp != nil
}

func (p *MessageBlock) IsSetCreateTimestamp() bool {
	return p.CreateTimestamp != nil
}

func (p *MessageBlock) IsSetCreateTimestampList() bool {
	return p.CreateTimestampList != nil
}

func (p *MessageBlock) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		case 6:
			if err := p.ReadField6(iprot); err != nil {
				return err
			}
		case 7:
			if err := p.ReadField7(iprot); err != nil {
				return err
			}
		case 8:
			if err := p.ReadField8(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *MessageBlock) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 1: %s", err)
	} else {
		p.StartMessageOffset = v
	}
	return nil
}

func (p *MessageBlock) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.MessageNumber = v
	}
	return nil
}

func (p *MessageBlock) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		temp := MessageCompressionType(v)
		p.CompressionType = temp
	}
	return nil
}

func (p *MessageBlock) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(); err != nil {
		return fmt.Errorf("error reading field 4: %s", err)
	} else {
		p.MessageBlock = v
	}
	return nil
}

func (p *MessageBlock) ReadField5(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 5: %s", err)
	} else {
		p.MessageBlockSize = &v
	}
	return nil
}

func (p *MessageBlock) ReadField6(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 6: %s", err)
	} else {
		p.AppendTimestamp = &v
	}
	return nil
}

func (p *MessageBlock) ReadField7(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 7: %s", err)
	} else {
		p.CreateTimestamp = &v
	}
	return nil
}

func (p *MessageBlock) ReadField8(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]int64, 0, size)
	p.CreateTimestampList = tSlice
	for i := 0; i < size; i++ {
		var _elem0 int64
		if v, err := iprot.ReadI64(); err != nil {
			return fmt.Errorf("error reading field 0: %s", err)
		} else {
			_elem0 = v
		}
		p.CreateTimestampList = append(p.CreateTimestampList, _elem0)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *MessageBlock) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("MessageBlock"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := p.writeField5(oprot); err != nil {
		return err
	}
	if err := p.writeField6(oprot); err != nil {
		return err
	}
	if err := p.writeField7(oprot); err != nil {
		return err
	}
	if err := p.writeField8(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *MessageBlock) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("startMessageOffset", thrift.I64, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:startMessageOffset: %s", p, err)
	}
	if err := oprot.WriteI64(int64(p.StartMessageOffset)); err != nil {
		return fmt.Errorf("%T.startMessageOffset (1) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:startMessageOffset: %s", p, err)
	}
	return err
}

func (p *MessageBlock) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("messageNumber", thrift.I32, 2); err != nil {
		return fmt.Errorf("%T write field begin error 2:messageNumber: %s", p, err)
	}
	if err := oprot.WriteI32(int32(p.MessageNumber)); err != nil {
		return fmt.Errorf("%T.messageNumber (2) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 2:messageNumber: %s", p, err)
	}
	return err
}

func (p *MessageBlock) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("compressionType", thrift.I32, 3); err != nil {
		return fmt.Errorf("%T write field begin error 3:compressionType: %s", p, err)
	}
	if err := oprot.WriteI32(int32(p.CompressionType)); err != nil {
		return fmt.Errorf("%T.compressionType (3) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 3:compressionType: %s", p, err)
	}
	return err
}

func (p *MessageBlock) writeField4(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("messageBlock", thrift.STRING, 4); err != nil {
		return fmt.Errorf("%T write field begin error 4:messageBlock: %s", p, err)
	}
	if err := oprot.WriteBinary(p.MessageBlock); err != nil {
		return fmt.Errorf("%T.messageBlock (4) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 4:messageBlock: %s", p, err)
	}
	return err
}

func (p *MessageBlock) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetMessageBlockSize() {
		if err := oprot.WriteFieldBegin("messageBlockSize", thrift.I32, 5); err != nil {
			return fmt.Errorf("%T write field begin error 5:messageBlockSize: %s", p, err)
		}
		if err := oprot.WriteI32(int32(*p.MessageBlockSize)); err != nil {
			return fmt.Errorf("%T.messageBlockSize (5) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 5:messageBlockSize: %s", p, err)
		}
	}
	return err
}

func (p *MessageBlock) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetAppendTimestamp() {
		if err := oprot.WriteFieldBegin("appendTimestamp", thrift.I64, 6); err != nil {
			return fmt.Errorf("%T write field begin error 6:appendTimestamp: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.AppendTimestamp)); err != nil {
			return fmt.Errorf("%T.appendTimestamp (6) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 6:appendTimestamp: %s", p, err)
		}
	}
	return err
}

func (p *MessageBlock) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetCreateTimestamp() {
		if err := oprot.WriteFieldBegin("createTimestamp", thrift.I64, 7); err != nil {
			return fmt.Errorf("%T write field begin error 7:createTimestamp: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.CreateTimestamp)); err != nil {
			return fmt.Errorf("%T.createTimestamp (7) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 7:createTimestamp: %s", p, err)
		}
	}
	return err
}

func (p *MessageBlock) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetCreateTimestampList() {
		if err := oprot.WriteFieldBegin("createTimestampList", thrift.LIST, 8); err != nil {
			return fmt.Errorf("%T write field begin error 8:createTimestampList: %s", p, err)
		}
		if err := oprot.WriteListBegin(thrift.I64, len(p.CreateTimestampList)); err != nil {
			return fmt.Errorf("error writing list begin: %s", err)
		}
		for _, v := range p.CreateTimestampList {
			if err := oprot.WriteI64(int64(v)); err != nil {
				return fmt.Errorf("%T. (0) field write error: %s", p, err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return fmt.Errorf("error writing list end: %s", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 8:createTimestampList: %s", p, err)
		}
	}
	return err
}

func (p *MessageBlock) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageBlock(%+v)", *p)
}

type PutMessageRequest struct {
	TopicAndPartition *topic.TopicAndPartition `thrift:"topicAndPartition,1,required" json:"topicAndPartition"`
	MessageBlocks     []*MessageBlock          `thrift:"messageBlocks,2,required" json:"messageBlocks"`
	MessageNumber     int32                    `thrift:"messageNumber,3,required" json:"messageNumber"`
	SequenceId        string                   `thrift:"sequenceId,4,required" json:"sequenceId"`
	TimeoutTimestamp  *int64                   `thrift:"timeoutTimestamp,5" json:"timeoutTimestamp"`
}

func NewPutMessageRequest() *PutMessageRequest {
	return &PutMessageRequest{}
}

var PutMessageRequest_TopicAndPartition_DEFAULT *topic.TopicAndPartition

func (p *PutMessageRequest) GetTopicAndPartition() *topic.TopicAndPartition {
	if !p.IsSetTopicAndPartition() {
		return PutMessageRequest_TopicAndPartition_DEFAULT
	}
	return p.TopicAndPartition
}

func (p *PutMessageRequest) GetMessageBlocks() []*MessageBlock {
	return p.MessageBlocks
}

func (p *PutMessageRequest) GetMessageNumber() int32 {
	return p.MessageNumber
}

func (p *PutMessageRequest) GetSequenceId() string {
	return p.SequenceId
}

var PutMessageRequest_TimeoutTimestamp_DEFAULT int64

func (p *PutMessageRequest) GetTimeoutTimestamp() int64 {
	if !p.IsSetTimeoutTimestamp() {
		return PutMessageRequest_TimeoutTimestamp_DEFAULT
	}
	return *p.TimeoutTimestamp
}
func (p *PutMessageRequest) IsSetTopicAndPartition() bool {
	return p.TopicAndPartition != nil
}

func (p *PutMessageRequest) IsSetTimeoutTimestamp() bool {
	return p.TimeoutTimestamp != nil
}

func (p *PutMessageRequest) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *PutMessageRequest) ReadField1(iprot thrift.TProtocol) error {
	p.TopicAndPartition = &topic.TopicAndPartition{}
	if err := p.TopicAndPartition.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.TopicAndPartition, err)
	}
	return nil
}

func (p *PutMessageRequest) ReadField2(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]*MessageBlock, 0, size)
	p.MessageBlocks = tSlice
	for i := 0; i < size; i++ {
		_elem1 := &MessageBlock{
			CompressionType: 0,
		}
		if err := _elem1.Read(iprot); err != nil {
			return fmt.Errorf("%T error reading struct: %s", _elem1, err)
		}
		p.MessageBlocks = append(p.MessageBlocks, _elem1)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *PutMessageRequest) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		p.MessageNumber = v
	}
	return nil
}

func (p *PutMessageRequest) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 4: %s", err)
	} else {
		p.SequenceId = v
	}
	return nil
}

func (p *PutMessageRequest) ReadField5(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 5: %s", err)
	} else {
		p.TimeoutTimestamp = &v
	}
	return nil
}

func (p *PutMessageRequest) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("PutMessageRequest"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := p.writeField5(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *PutMessageRequest) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("topicAndPartition", thrift.STRUCT, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:topicAndPartition: %s", p, err)
	}
	if err := p.TopicAndPartition.Write(oprot); err != nil {
		return fmt.Errorf("%T error writing struct: %s", p.TopicAndPartition, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:topicAndPartition: %s", p, err)
	}
	return err
}

func (p *PutMessageRequest) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("messageBlocks", thrift.LIST, 2); err != nil {
		return fmt.Errorf("%T write field begin error 2:messageBlocks: %s", p, err)
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.MessageBlocks)); err != nil {
		return fmt.Errorf("error writing list begin: %s", err)
	}
	for _, v := range p.MessageBlocks {
		if err := v.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", v, err)
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return fmt.Errorf("error writing list end: %s", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 2:messageBlocks: %s", p, err)
	}
	return err
}

func (p *PutMessageRequest) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("messageNumber", thrift.I32, 3); err != nil {
		return fmt.Errorf("%T write field begin error 3:messageNumber: %s", p, err)
	}
	if err := oprot.WriteI32(int32(p.MessageNumber)); err != nil {
		return fmt.Errorf("%T.messageNumber (3) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 3:messageNumber: %s", p, err)
	}
	return err
}

func (p *PutMessageRequest) writeField4(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("sequenceId", thrift.STRING, 4); err != nil {
		return fmt.Errorf("%T write field begin error 4:sequenceId: %s", p, err)
	}
	if err := oprot.WriteString(string(p.SequenceId)); err != nil {
		return fmt.Errorf("%T.sequenceId (4) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 4:sequenceId: %s", p, err)
	}
	return err
}

func (p *PutMessageRequest) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetTimeoutTimestamp() {
		if err := oprot.WriteFieldBegin("timeoutTimestamp", thrift.I64, 5); err != nil {
			return fmt.Errorf("%T write field begin error 5:timeoutTimestamp: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.TimeoutTimestamp)); err != nil {
			return fmt.Errorf("%T.timeoutTimestamp (5) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 5:timeoutTimestamp: %s", p, err)
		}
	}
	return err
}

func (p *PutMessageRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PutMessageRequest(%+v)", *p)
}

type PutMessageResponse struct {
	SequenceId string `thrift:"sequenceId,1,required" json:"sequenceId"`
	IsTransfer *bool  `thrift:"isTransfer,2" json:"isTransfer"`
}

func NewPutMessageResponse() *PutMessageResponse {
	return &PutMessageResponse{}
}

func (p *PutMessageResponse) GetSequenceId() string {
	return p.SequenceId
}

var PutMessageResponse_IsTransfer_DEFAULT bool

func (p *PutMessageResponse) GetIsTransfer() bool {
	if !p.IsSetIsTransfer() {
		return PutMessageResponse_IsTransfer_DEFAULT
	}
	return *p.IsTransfer
}
func (p *PutMessageResponse) IsSetIsTransfer() bool {
	return p.IsTransfer != nil
}

func (p *PutMessageResponse) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *PutMessageResponse) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 1: %s", err)
	} else {
		p.SequenceId = v
	}
	return nil
}

func (p *PutMessageResponse) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.IsTransfer = &v
	}
	return nil
}

func (p *PutMessageResponse) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("PutMessageResponse"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *PutMessageResponse) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("sequenceId", thrift.STRING, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:sequenceId: %s", p, err)
	}
	if err := oprot.WriteString(string(p.SequenceId)); err != nil {
		return fmt.Errorf("%T.sequenceId (1) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:sequenceId: %s", p, err)
	}
	return err
}

func (p *PutMessageResponse) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetIsTransfer() {
		if err := oprot.WriteFieldBegin("isTransfer", thrift.BOOL, 2); err != nil {
			return fmt.Errorf("%T write field begin error 2:isTransfer: %s", p, err)
		}
		if err := oprot.WriteBool(bool(*p.IsTransfer)); err != nil {
			return fmt.Errorf("%T.isTransfer (2) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 2:isTransfer: %s", p, err)
		}
	}
	return err
}

func (p *PutMessageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PutMessageResponse(%+v)", *p)
}

type GetMessageRequest struct {
	TopicAndPartition *topic.TopicAndPartition `thrift:"topicAndPartition,1,required" json:"topicAndPartition"`
	// unused field # 2
	MessageOffset              int64  `thrift:"messageOffset,3,required" json:"messageOffset"`
	MaxGetMessageNumber        int32  `thrift:"maxGetMessageNumber,4" json:"maxGetMessageNumber"`
	MaxGetMessageBytes         int32  `thrift:"maxGetMessageBytes,5" json:"maxGetMessageBytes"`
	ShowUnHandledMessageNumber bool   `thrift:"showUnHandledMessageNumber,6" json:"showUnHandledMessageNumber"`
	SequenceId                 string `thrift:"sequenceId,7,required" json:"sequenceId"`
	TimeoutTimestamp           *int64 `thrift:"timeoutTimestamp,8" json:"timeoutTimestamp"`
}

func NewGetMessageRequest() *GetMessageRequest {
	return &GetMessageRequest{
		MaxGetMessageNumber: 2000,

		MaxGetMessageBytes: 10485760,

		ShowUnHandledMessageNumber: true,
	}
}

var GetMessageRequest_TopicAndPartition_DEFAULT *topic.TopicAndPartition

func (p *GetMessageRequest) GetTopicAndPartition() *topic.TopicAndPartition {
	if !p.IsSetTopicAndPartition() {
		return GetMessageRequest_TopicAndPartition_DEFAULT
	}
	return p.TopicAndPartition
}

func (p *GetMessageRequest) GetMessageOffset() int64 {
	return p.MessageOffset
}

var GetMessageRequest_MaxGetMessageNumber_DEFAULT int32 = 2000

func (p *GetMessageRequest) GetMaxGetMessageNumber() int32 {
	return p.MaxGetMessageNumber
}

var GetMessageRequest_MaxGetMessageBytes_DEFAULT int32 = 10485760

func (p *GetMessageRequest) GetMaxGetMessageBytes() int32 {
	return p.MaxGetMessageBytes
}

var GetMessageRequest_ShowUnHandledMessageNumber_DEFAULT bool = true

func (p *GetMessageRequest) GetShowUnHandledMessageNumber() bool {
	return p.ShowUnHandledMessageNumber
}

func (p *GetMessageRequest) GetSequenceId() string {
	return p.SequenceId
}

var GetMessageRequest_TimeoutTimestamp_DEFAULT int64

func (p *GetMessageRequest) GetTimeoutTimestamp() int64 {
	if !p.IsSetTimeoutTimestamp() {
		return GetMessageRequest_TimeoutTimestamp_DEFAULT
	}
	return *p.TimeoutTimestamp
}
func (p *GetMessageRequest) IsSetTopicAndPartition() bool {
	return p.TopicAndPartition != nil
}

func (p *GetMessageRequest) IsSetMaxGetMessageNumber() bool {
	return p.MaxGetMessageNumber != GetMessageRequest_MaxGetMessageNumber_DEFAULT
}

func (p *GetMessageRequest) IsSetMaxGetMessageBytes() bool {
	return p.MaxGetMessageBytes != GetMessageRequest_MaxGetMessageBytes_DEFAULT
}

func (p *GetMessageRequest) IsSetShowUnHandledMessageNumber() bool {
	return p.ShowUnHandledMessageNumber != GetMessageRequest_ShowUnHandledMessageNumber_DEFAULT
}

func (p *GetMessageRequest) IsSetTimeoutTimestamp() bool {
	return p.TimeoutTimestamp != nil
}

func (p *GetMessageRequest) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		case 6:
			if err := p.ReadField6(iprot); err != nil {
				return err
			}
		case 7:
			if err := p.ReadField7(iprot); err != nil {
				return err
			}
		case 8:
			if err := p.ReadField8(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *GetMessageRequest) ReadField1(iprot thrift.TProtocol) error {
	p.TopicAndPartition = &topic.TopicAndPartition{}
	if err := p.TopicAndPartition.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.TopicAndPartition, err)
	}
	return nil
}

func (p *GetMessageRequest) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		p.MessageOffset = v
	}
	return nil
}

func (p *GetMessageRequest) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 4: %s", err)
	} else {
		p.MaxGetMessageNumber = v
	}
	return nil
}

func (p *GetMessageRequest) ReadField5(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 5: %s", err)
	} else {
		p.MaxGetMessageBytes = v
	}
	return nil
}

func (p *GetMessageRequest) ReadField6(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return fmt.Errorf("error reading field 6: %s", err)
	} else {
		p.ShowUnHandledMessageNumber = v
	}
	return nil
}

func (p *GetMessageRequest) ReadField7(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 7: %s", err)
	} else {
		p.SequenceId = v
	}
	return nil
}

func (p *GetMessageRequest) ReadField8(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 8: %s", err)
	} else {
		p.TimeoutTimestamp = &v
	}
	return nil
}

func (p *GetMessageRequest) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetMessageRequest"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := p.writeField5(oprot); err != nil {
		return err
	}
	if err := p.writeField6(oprot); err != nil {
		return err
	}
	if err := p.writeField7(oprot); err != nil {
		return err
	}
	if err := p.writeField8(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *GetMessageRequest) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("topicAndPartition", thrift.STRUCT, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:topicAndPartition: %s", p, err)
	}
	if err := p.TopicAndPartition.Write(oprot); err != nil {
		return fmt.Errorf("%T error writing struct: %s", p.TopicAndPartition, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:topicAndPartition: %s", p, err)
	}
	return err
}

func (p *GetMessageRequest) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("messageOffset", thrift.I64, 3); err != nil {
		return fmt.Errorf("%T write field begin error 3:messageOffset: %s", p, err)
	}
	if err := oprot.WriteI64(int64(p.MessageOffset)); err != nil {
		return fmt.Errorf("%T.messageOffset (3) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 3:messageOffset: %s", p, err)
	}
	return err
}

func (p *GetMessageRequest) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetMaxGetMessageNumber() {
		if err := oprot.WriteFieldBegin("maxGetMessageNumber", thrift.I32, 4); err != nil {
			return fmt.Errorf("%T write field begin error 4:maxGetMessageNumber: %s", p, err)
		}
		if err := oprot.WriteI32(int32(p.MaxGetMessageNumber)); err != nil {
			return fmt.Errorf("%T.maxGetMessageNumber (4) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 4:maxGetMessageNumber: %s", p, err)
		}
	}
	return err
}

func (p *GetMessageRequest) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetMaxGetMessageBytes() {
		if err := oprot.WriteFieldBegin("maxGetMessageBytes", thrift.I32, 5); err != nil {
			return fmt.Errorf("%T write field begin error 5:maxGetMessageBytes: %s", p, err)
		}
		if err := oprot.WriteI32(int32(p.MaxGetMessageBytes)); err != nil {
			return fmt.Errorf("%T.maxGetMessageBytes (5) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 5:maxGetMessageBytes: %s", p, err)
		}
	}
	return err
}

func (p *GetMessageRequest) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetShowUnHandledMessageNumber() {
		if err := oprot.WriteFieldBegin("showUnHandledMessageNumber", thrift.BOOL, 6); err != nil {
			return fmt.Errorf("%T write field begin error 6:showUnHandledMessageNumber: %s", p, err)
		}
		if err := oprot.WriteBool(bool(p.ShowUnHandledMessageNumber)); err != nil {
			return fmt.Errorf("%T.showUnHandledMessageNumber (6) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 6:showUnHandledMessageNumber: %s", p, err)
		}
	}
	return err
}

func (p *GetMessageRequest) writeField7(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("sequenceId", thrift.STRING, 7); err != nil {
		return fmt.Errorf("%T write field begin error 7:sequenceId: %s", p, err)
	}
	if err := oprot.WriteString(string(p.SequenceId)); err != nil {
		return fmt.Errorf("%T.sequenceId (7) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 7:sequenceId: %s", p, err)
	}
	return err
}

func (p *GetMessageRequest) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetTimeoutTimestamp() {
		if err := oprot.WriteFieldBegin("timeoutTimestamp", thrift.I64, 8); err != nil {
			return fmt.Errorf("%T write field begin error 8:timeoutTimestamp: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.TimeoutTimestamp)); err != nil {
			return fmt.Errorf("%T.timeoutTimestamp (8) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 8:timeoutTimestamp: %s", p, err)
		}
	}
	return err
}

func (p *GetMessageRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMessageRequest(%+v)", *p)
}

type GetMessageResponse struct {
	MessageBlocks          []*MessageBlock `thrift:"messageBlocks,1,required" json:"messageBlocks"`
	MessageNumber          int32           `thrift:"messageNumber,2,required" json:"messageNumber"`
	UnHandledMessageNumber *int64          `thrift:"unHandledMessageNumber,3" json:"unHandledMessageNumber"`
	SequenceId             string          `thrift:"sequenceId,4,required" json:"sequenceId"`
	IsTransfer             *bool           `thrift:"isTransfer,5" json:"isTransfer"`
}

func NewGetMessageResponse() *GetMessageResponse {
	return &GetMessageResponse{}
}

func (p *GetMessageResponse) GetMessageBlocks() []*MessageBlock {
	return p.MessageBlocks
}

func (p *GetMessageResponse) GetMessageNumber() int32 {
	return p.MessageNumber
}

var GetMessageResponse_UnHandledMessageNumber_DEFAULT int64

func (p *GetMessageResponse) GetUnHandledMessageNumber() int64 {
	if !p.IsSetUnHandledMessageNumber() {
		return GetMessageResponse_UnHandledMessageNumber_DEFAULT
	}
	return *p.UnHandledMessageNumber
}

func (p *GetMessageResponse) GetSequenceId() string {
	return p.SequenceId
}

var GetMessageResponse_IsTransfer_DEFAULT bool

func (p *GetMessageResponse) GetIsTransfer() bool {
	if !p.IsSetIsTransfer() {
		return GetMessageResponse_IsTransfer_DEFAULT
	}
	return *p.IsTransfer
}
func (p *GetMessageResponse) IsSetUnHandledMessageNumber() bool {
	return p.UnHandledMessageNumber != nil
}

func (p *GetMessageResponse) IsSetIsTransfer() bool {
	return p.IsTransfer != nil
}

func (p *GetMessageResponse) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *GetMessageResponse) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]*MessageBlock, 0, size)
	p.MessageBlocks = tSlice
	for i := 0; i < size; i++ {
		_elem2 := &MessageBlock{
			CompressionType: 0,
		}
		if err := _elem2.Read(iprot); err != nil {
			return fmt.Errorf("%T error reading struct: %s", _elem2, err)
		}
		p.MessageBlocks = append(p.MessageBlocks, _elem2)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *GetMessageResponse) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.MessageNumber = v
	}
	return nil
}

func (p *GetMessageResponse) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		p.UnHandledMessageNumber = &v
	}
	return nil
}

func (p *GetMessageResponse) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 4: %s", err)
	} else {
		p.SequenceId = v
	}
	return nil
}

func (p *GetMessageResponse) ReadField5(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return fmt.Errorf("error reading field 5: %s", err)
	} else {
		p.IsTransfer = &v
	}
	return nil
}

func (p *GetMessageResponse) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetMessageResponse"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := p.writeField5(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *GetMessageResponse) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("messageBlocks", thrift.LIST, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:messageBlocks: %s", p, err)
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.MessageBlocks)); err != nil {
		return fmt.Errorf("error writing list begin: %s", err)
	}
	for _, v := range p.MessageBlocks {
		if err := v.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", v, err)
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return fmt.Errorf("error writing list end: %s", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:messageBlocks: %s", p, err)
	}
	return err
}

func (p *GetMessageResponse) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("messageNumber", thrift.I32, 2); err != nil {
		return fmt.Errorf("%T write field begin error 2:messageNumber: %s", p, err)
	}
	if err := oprot.WriteI32(int32(p.MessageNumber)); err != nil {
		return fmt.Errorf("%T.messageNumber (2) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 2:messageNumber: %s", p, err)
	}
	return err
}

func (p *GetMessageResponse) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetUnHandledMessageNumber() {
		if err := oprot.WriteFieldBegin("unHandledMessageNumber", thrift.I64, 3); err != nil {
			return fmt.Errorf("%T write field begin error 3:unHandledMessageNumber: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.UnHandledMessageNumber)); err != nil {
			return fmt.Errorf("%T.unHandledMessageNumber (3) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 3:unHandledMessageNumber: %s", p, err)
		}
	}
	return err
}

func (p *GetMessageResponse) writeField4(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("sequenceId", thrift.STRING, 4); err != nil {
		return fmt.Errorf("%T write field begin error 4:sequenceId: %s", p, err)
	}
	if err := oprot.WriteString(string(p.SequenceId)); err != nil {
		return fmt.Errorf("%T.sequenceId (4) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 4:sequenceId: %s", p, err)
	}
	return err
}

func (p *GetMessageResponse) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetIsTransfer() {
		if err := oprot.WriteFieldBegin("isTransfer", thrift.BOOL, 5); err != nil {
			return fmt.Errorf("%T write field begin error 5:isTransfer: %s", p, err)
		}
		if err := oprot.WriteBool(bool(*p.IsTransfer)); err != nil {
			return fmt.Errorf("%T.isTransfer (5) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 5:isTransfer: %s", p, err)
		}
	}
	return err
}

func (p *GetMessageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMessageResponse(%+v)", *p)
}

type OffsetInfo struct {
	PartitionId int32             `thrift:"partitionId,1,required" json:"partitionId"`
	StartOffset *int64            `thrift:"startOffset,2" json:"startOffset"`
	EndOffset   *int64            `thrift:"endOffset,3" json:"endOffset"`
	ErrorCode   *common.ErrorCode `thrift:"errorCode,4" json:"errorCode"`
	ErrorMsg    *string           `thrift:"errorMsg,5" json:"errorMsg"`
}

func NewOffsetInfo() *OffsetInfo {
	return &OffsetInfo{}
}

func (p *OffsetInfo) GetPartitionId() int32 {
	return p.PartitionId
}

var OffsetInfo_StartOffset_DEFAULT int64

func (p *OffsetInfo) GetStartOffset() int64 {
	if !p.IsSetStartOffset() {
		return OffsetInfo_StartOffset_DEFAULT
	}
	return *p.StartOffset
}

var OffsetInfo_EndOffset_DEFAULT int64

func (p *OffsetInfo) GetEndOffset() int64 {
	if !p.IsSetEndOffset() {
		return OffsetInfo_EndOffset_DEFAULT
	}
	return *p.EndOffset
}

var OffsetInfo_ErrorCode_DEFAULT common.ErrorCode

func (p *OffsetInfo) GetErrorCode() common.ErrorCode {
	if !p.IsSetErrorCode() {
		return OffsetInfo_ErrorCode_DEFAULT
	}
	return *p.ErrorCode
}

var OffsetInfo_ErrorMsg_DEFAULT string

func (p *OffsetInfo) GetErrorMsg() string {
	if !p.IsSetErrorMsg() {
		return OffsetInfo_ErrorMsg_DEFAULT
	}
	return *p.ErrorMsg
}
func (p *OffsetInfo) IsSetStartOffset() bool {
	return p.StartOffset != nil
}

func (p *OffsetInfo) IsSetEndOffset() bool {
	return p.EndOffset != nil
}

func (p *OffsetInfo) IsSetErrorCode() bool {
	return p.ErrorCode != nil
}

func (p *OffsetInfo) IsSetErrorMsg() bool {
	return p.ErrorMsg != nil
}

func (p *OffsetInfo) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *OffsetInfo) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 1: %s", err)
	} else {
		p.PartitionId = v
	}
	return nil
}

func (p *OffsetInfo) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.StartOffset = &v
	}
	return nil
}

func (p *OffsetInfo) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		p.EndOffset = &v
	}
	return nil
}

func (p *OffsetInfo) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 4: %s", err)
	} else {
		temp := common.ErrorCode(v)
		p.ErrorCode = &temp
	}
	return nil
}

func (p *OffsetInfo) ReadField5(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 5: %s", err)
	} else {
		p.ErrorMsg = &v
	}
	return nil
}

func (p *OffsetInfo) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("OffsetInfo"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := p.writeField5(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *OffsetInfo) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("partitionId", thrift.I32, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:partitionId: %s", p, err)
	}
	if err := oprot.WriteI32(int32(p.PartitionId)); err != nil {
		return fmt.Errorf("%T.partitionId (1) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:partitionId: %s", p, err)
	}
	return err
}

func (p *OffsetInfo) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetStartOffset() {
		if err := oprot.WriteFieldBegin("startOffset", thrift.I64, 2); err != nil {
			return fmt.Errorf("%T write field begin error 2:startOffset: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.StartOffset)); err != nil {
			return fmt.Errorf("%T.startOffset (2) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 2:startOffset: %s", p, err)
		}
	}
	return err
}

func (p *OffsetInfo) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetEndOffset() {
		if err := oprot.WriteFieldBegin("endOffset", thrift.I64, 3); err != nil {
			return fmt.Errorf("%T write field begin error 3:endOffset: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.EndOffset)); err != nil {
			return fmt.Errorf("%T.endOffset (3) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 3:endOffset: %s", p, err)
		}
	}
	return err
}

func (p *OffsetInfo) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetErrorCode() {
		if err := oprot.WriteFieldBegin("errorCode", thrift.I32, 4); err != nil {
			return fmt.Errorf("%T write field begin error 4:errorCode: %s", p, err)
		}
		if err := oprot.WriteI32(int32(*p.ErrorCode)); err != nil {
			return fmt.Errorf("%T.errorCode (4) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 4:errorCode: %s", p, err)
		}
	}
	return err
}

func (p *OffsetInfo) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetErrorMsg() {
		if err := oprot.WriteFieldBegin("errorMsg", thrift.STRING, 5); err != nil {
			return fmt.Errorf("%T write field begin error 5:errorMsg: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.ErrorMsg)); err != nil {
			return fmt.Errorf("%T.errorMsg (5) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 5:errorMsg: %s", p, err)
		}
	}
	return err
}

func (p *OffsetInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OffsetInfo(%+v)", *p)
}

type GetTopicOffsetRequest struct {
	TopicTalosResourceName *topic.TopicTalosResourceName `thrift:"topicTalosResourceName,1,required" json:"topicTalosResourceName"`
}

func NewGetTopicOffsetRequest() *GetTopicOffsetRequest {
	return &GetTopicOffsetRequest{}
}

var GetTopicOffsetRequest_TopicTalosResourceName_DEFAULT *topic.TopicTalosResourceName

func (p *GetTopicOffsetRequest) GetTopicTalosResourceName() *topic.TopicTalosResourceName {
	if !p.IsSetTopicTalosResourceName() {
		return GetTopicOffsetRequest_TopicTalosResourceName_DEFAULT
	}
	return p.TopicTalosResourceName
}
func (p *GetTopicOffsetRequest) IsSetTopicTalosResourceName() bool {
	return p.TopicTalosResourceName != nil
}

func (p *GetTopicOffsetRequest) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *GetTopicOffsetRequest) ReadField1(iprot thrift.TProtocol) error {
	p.TopicTalosResourceName = &topic.TopicTalosResourceName{}
	if err := p.TopicTalosResourceName.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.TopicTalosResourceName, err)
	}
	return nil
}

func (p *GetTopicOffsetRequest) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetTopicOffsetRequest"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *GetTopicOffsetRequest) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("topicTalosResourceName", thrift.STRUCT, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:topicTalosResourceName: %s", p, err)
	}
	if err := p.TopicTalosResourceName.Write(oprot); err != nil {
		return fmt.Errorf("%T error writing struct: %s", p.TopicTalosResourceName, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:topicTalosResourceName: %s", p, err)
	}
	return err
}

func (p *GetTopicOffsetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTopicOffsetRequest(%+v)", *p)
}

type GetTopicOffsetResponse struct {
	OffsetInfoList []*OffsetInfo `thrift:"offsetInfoList,1,required" json:"offsetInfoList"`
}

func NewGetTopicOffsetResponse() *GetTopicOffsetResponse {
	return &GetTopicOffsetResponse{}
}

func (p *GetTopicOffsetResponse) GetOffsetInfoList() []*OffsetInfo {
	return p.OffsetInfoList
}
func (p *GetTopicOffsetResponse) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *GetTopicOffsetResponse) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]*OffsetInfo, 0, size)
	p.OffsetInfoList = tSlice
	for i := 0; i < size; i++ {
		_elem3 := &OffsetInfo{}
		if err := _elem3.Read(iprot); err != nil {
			return fmt.Errorf("%T error reading struct: %s", _elem3, err)
		}
		p.OffsetInfoList = append(p.OffsetInfoList, _elem3)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *GetTopicOffsetResponse) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetTopicOffsetResponse"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *GetTopicOffsetResponse) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("offsetInfoList", thrift.LIST, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:offsetInfoList: %s", p, err)
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.OffsetInfoList)); err != nil {
		return fmt.Errorf("error writing list begin: %s", err)
	}
	for _, v := range p.OffsetInfoList {
		if err := v.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", v, err)
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return fmt.Errorf("error writing list end: %s", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:offsetInfoList: %s", p, err)
	}
	return err
}

func (p *GetTopicOffsetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTopicOffsetResponse(%+v)", *p)
}

type GetPartitionOffsetRequest struct {
	TopicAndPartition *topic.TopicAndPartition `thrift:"topicAndPartition,1,required" json:"topicAndPartition"`
}

func NewGetPartitionOffsetRequest() *GetPartitionOffsetRequest {
	return &GetPartitionOffsetRequest{}
}

var GetPartitionOffsetRequest_TopicAndPartition_DEFAULT *topic.TopicAndPartition

func (p *GetPartitionOffsetRequest) GetTopicAndPartition() *topic.TopicAndPartition {
	if !p.IsSetTopicAndPartition() {
		return GetPartitionOffsetRequest_TopicAndPartition_DEFAULT
	}
	return p.TopicAndPartition
}
func (p *GetPartitionOffsetRequest) IsSetTopicAndPartition() bool {
	return p.TopicAndPartition != nil
}

func (p *GetPartitionOffsetRequest) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *GetPartitionOffsetRequest) ReadField1(iprot thrift.TProtocol) error {
	p.TopicAndPartition = &topic.TopicAndPartition{}
	if err := p.TopicAndPartition.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.TopicAndPartition, err)
	}
	return nil
}

func (p *GetPartitionOffsetRequest) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetPartitionOffsetRequest"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *GetPartitionOffsetRequest) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("topicAndPartition", thrift.STRUCT, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:topicAndPartition: %s", p, err)
	}
	if err := p.TopicAndPartition.Write(oprot); err != nil {
		return fmt.Errorf("%T error writing struct: %s", p.TopicAndPartition, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:topicAndPartition: %s", p, err)
	}
	return err
}

func (p *GetPartitionOffsetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPartitionOffsetRequest(%+v)", *p)
}

type GetPartitionOffsetResponse struct {
	OffsetInfo *OffsetInfo `thrift:"offsetInfo,1,required" json:"offsetInfo"`
}

func NewGetPartitionOffsetResponse() *GetPartitionOffsetResponse {
	return &GetPartitionOffsetResponse{}
}

var GetPartitionOffsetResponse_OffsetInfo_DEFAULT *OffsetInfo

func (p *GetPartitionOffsetResponse) GetOffsetInfo() *OffsetInfo {
	if !p.IsSetOffsetInfo() {
		return GetPartitionOffsetResponse_OffsetInfo_DEFAULT
	}
	return p.OffsetInfo
}
func (p *GetPartitionOffsetResponse) IsSetOffsetInfo() bool {
	return p.OffsetInfo != nil
}

func (p *GetPartitionOffsetResponse) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *GetPartitionOffsetResponse) ReadField1(iprot thrift.TProtocol) error {
	p.OffsetInfo = &OffsetInfo{}
	if err := p.OffsetInfo.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.OffsetInfo, err)
	}
	return nil
}

func (p *GetPartitionOffsetResponse) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetPartitionOffsetResponse"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *GetPartitionOffsetResponse) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("offsetInfo", thrift.STRUCT, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:offsetInfo: %s", p, err)
	}
	if err := p.OffsetInfo.Write(oprot); err != nil {
		return fmt.Errorf("%T error writing struct: %s", p.OffsetInfo, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:offsetInfo: %s", p, err)
	}
	return err
}

func (p *GetPartitionOffsetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPartitionOffsetResponse(%+v)", *p)
}

type GetPartitionsOffsetRequest struct {
	TopicAndPartitionList []*topic.TopicAndPartition `thrift:"topicAndPartitionList,1,required" json:"topicAndPartitionList"`
}

func NewGetPartitionsOffsetRequest() *GetPartitionsOffsetRequest {
	return &GetPartitionsOffsetRequest{}
}

func (p *GetPartitionsOffsetRequest) GetTopicAndPartitionList() []*topic.TopicAndPartition {
	return p.TopicAndPartitionList
}
func (p *GetPartitionsOffsetRequest) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *GetPartitionsOffsetRequest) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]*topic.TopicAndPartition, 0, size)
	p.TopicAndPartitionList = tSlice
	for i := 0; i < size; i++ {
		_elem4 := &topic.TopicAndPartition{}
		if err := _elem4.Read(iprot); err != nil {
			return fmt.Errorf("%T error reading struct: %s", _elem4, err)
		}
		p.TopicAndPartitionList = append(p.TopicAndPartitionList, _elem4)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *GetPartitionsOffsetRequest) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetPartitionsOffsetRequest"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *GetPartitionsOffsetRequest) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("topicAndPartitionList", thrift.LIST, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:topicAndPartitionList: %s", p, err)
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.TopicAndPartitionList)); err != nil {
		return fmt.Errorf("error writing list begin: %s", err)
	}
	for _, v := range p.TopicAndPartitionList {
		if err := v.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", v, err)
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return fmt.Errorf("error writing list end: %s", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:topicAndPartitionList: %s", p, err)
	}
	return err
}

func (p *GetPartitionsOffsetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPartitionsOffsetRequest(%+v)", *p)
}

type GetPartitionsOffsetResponse struct {
	OffsetInfoList []*OffsetInfo `thrift:"offsetInfoList,1,required" json:"offsetInfoList"`
}

func NewGetPartitionsOffsetResponse() *GetPartitionsOffsetResponse {
	return &GetPartitionsOffsetResponse{}
}

func (p *GetPartitionsOffsetResponse) GetOffsetInfoList() []*OffsetInfo {
	return p.OffsetInfoList
}
func (p *GetPartitionsOffsetResponse) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *GetPartitionsOffsetResponse) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]*OffsetInfo, 0, size)
	p.OffsetInfoList = tSlice
	for i := 0; i < size; i++ {
		_elem5 := &OffsetInfo{}
		if err := _elem5.Read(iprot); err != nil {
			return fmt.Errorf("%T error reading struct: %s", _elem5, err)
		}
		p.OffsetInfoList = append(p.OffsetInfoList, _elem5)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *GetPartitionsOffsetResponse) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetPartitionsOffsetResponse"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *GetPartitionsOffsetResponse) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("offsetInfoList", thrift.LIST, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:offsetInfoList: %s", p, err)
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.OffsetInfoList)); err != nil {
		return fmt.Errorf("error writing list begin: %s", err)
	}
	for _, v := range p.OffsetInfoList {
		if err := v.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", v, err)
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return fmt.Errorf("error writing list end: %s", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:offsetInfoList: %s", p, err)
	}
	return err
}

func (p *GetPartitionsOffsetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPartitionsOffsetResponse(%+v)", *p)
}

type GetScheduleInfoRequest struct {
	TopicTalosResourceName *topic.TopicTalosResourceName `thrift:"topicTalosResourceName,1,required" json:"topicTalosResourceName"`
}

func NewGetScheduleInfoRequest() *GetScheduleInfoRequest {
	return &GetScheduleInfoRequest{}
}

var GetScheduleInfoRequest_TopicTalosResourceName_DEFAULT *topic.TopicTalosResourceName

func (p *GetScheduleInfoRequest) GetTopicTalosResourceName() *topic.TopicTalosResourceName {
	if !p.IsSetTopicTalosResourceName() {
		return GetScheduleInfoRequest_TopicTalosResourceName_DEFAULT
	}
	return p.TopicTalosResourceName
}
func (p *GetScheduleInfoRequest) IsSetTopicTalosResourceName() bool {
	return p.TopicTalosResourceName != nil
}

func (p *GetScheduleInfoRequest) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *GetScheduleInfoRequest) ReadField1(iprot thrift.TProtocol) error {
	p.TopicTalosResourceName = &topic.TopicTalosResourceName{}
	if err := p.TopicTalosResourceName.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.TopicTalosResourceName, err)
	}
	return nil
}

func (p *GetScheduleInfoRequest) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetScheduleInfoRequest"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *GetScheduleInfoRequest) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("topicTalosResourceName", thrift.STRUCT, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:topicTalosResourceName: %s", p, err)
	}
	if err := p.TopicTalosResourceName.Write(oprot); err != nil {
		return fmt.Errorf("%T error writing struct: %s", p.TopicTalosResourceName, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:topicTalosResourceName: %s", p, err)
	}
	return err
}

func (p *GetScheduleInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetScheduleInfoRequest(%+v)", *p)
}

type GetScheduleInfoResponse struct {
	ScheduleInfo map[*topic.TopicAndPartition]string `thrift:"scheduleInfo,1,required" json:"scheduleInfo"`
}

func NewGetScheduleInfoResponse() *GetScheduleInfoResponse {
	return &GetScheduleInfoResponse{}
}

func (p *GetScheduleInfoResponse) GetScheduleInfo() map[*topic.TopicAndPartition]string {
	return p.ScheduleInfo
}
func (p *GetScheduleInfoResponse) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *GetScheduleInfoResponse) ReadField1(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return fmt.Errorf("error reading map begin: %s", err)
	}
	tMap := make(map[*topic.TopicAndPartition]string, size)
	p.ScheduleInfo = tMap
	for i := 0; i < size; i++ {
		_key6 := &topic.TopicAndPartition{}
		if err := _key6.Read(iprot); err != nil {
			return fmt.Errorf("%T error reading struct: %s", _key6, err)
		}
		var _val7 string
		if v, err := iprot.ReadString(); err != nil {
			return fmt.Errorf("error reading field 0: %s", err)
		} else {
			_val7 = v
		}
		p.ScheduleInfo[_key6] = _val7
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return fmt.Errorf("error reading map end: %s", err)
	}
	return nil
}

func (p *GetScheduleInfoResponse) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetScheduleInfoResponse"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *GetScheduleInfoResponse) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("scheduleInfo", thrift.MAP, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:scheduleInfo: %s", p, err)
	}
	if err := oprot.WriteMapBegin(thrift.STRUCT, thrift.STRING, len(p.ScheduleInfo)); err != nil {
		return fmt.Errorf("error writing map begin: %s", err)
	}
	for k, v := range p.ScheduleInfo {
		if err := k.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", k, err)
		}
		if err := oprot.WriteString(string(v)); err != nil {
			return fmt.Errorf("%T. (0) field write error: %s", p, err)
		}
	}
	if err := oprot.WriteMapEnd(); err != nil {
		return fmt.Errorf("error writing map end: %s", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:scheduleInfo: %s", p, err)
	}
	return err
}

func (p *GetScheduleInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetScheduleInfoResponse(%+v)", *p)
}
